# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-21 10:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('root', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='matching_set',
            field=models.ManyToManyField(blank=True, to='root.Matching'),
        ),
    ]
